-- MySQL Script generated by MySQL Workbench
-- Sat Jun 10 03:41:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema workbenchmanager
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `workbenchmanager` ;

-- -----------------------------------------------------
-- Schema workbenchmanager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `workbenchmanager` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
SHOW WARNINGS;
USE `workbenchmanager` ;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`Marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`Marcas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`Marcas` (
  `id` INT NOT NULL,
  `Slug` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT ``
    FOREIGN KEY ()
    REFERENCES `workbenchmanager`.`vehiculo` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`chat_messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`chat_messages` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`chat_messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message_content` TEXT NOT NULL,
  `timestamp` TIME NOT NULL,
  `id_sender` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15795
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`connected_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`connected_users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`connected_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `empleados_id` INT NOT NULL,
  PRIMARY KEY (`id`, `empleados_id`),
  UNIQUE INDEX `unique_username` (`username` ASC) ,
  CONSTRAINT `fk_connected_users_empleados1`
    FOREIGN KEY (`id`)
    REFERENCES `workbenchmanager`.`empleados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 700
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`datos_personales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`datos_personales` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`datos_personales` (
  `dni` VARCHAR(9) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `cliente` BIT(1) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `iban` VARCHAR(24) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`empleados` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`empleados` (
  `id` INT NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `empleados_ibfk_2` (`dni` ASC) ,
  CONSTRAINT `empleados_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `workbenchmanager`.`usuario_interno` (`id_usuario`),
  CONSTRAINT `empleados_ibfk_2`
    FOREIGN KEY (`dni`)
    REFERENCES `workbenchmanager`.`datos_personales` (`dni`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`facturas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`facturas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`facturas` (
  `idFactura` INT NOT NULL AUTO_INCREMENT,
  `cliente` VARCHAR(9) NOT NULL,
  `fechaEmision` DATE NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `pdf` VARCHAR(255) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `datos_personales_dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_facturas_datos_personales1_idx` (`cliente` ASC) ,
  CONSTRAINT `fk_facturas_datos_personales1`
    FOREIGN KEY (`cliente`)
    REFERENCES `workbenchmanager`.`datos_personales` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`horas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`horas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`horas` (
  `id` INT NOT NULL DEFAULT NULL,
  `horas` TIME NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  INDEX `id` (`id` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `horas_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `workbenchmanager`.`empleados` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`marcasMoto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`marcasMoto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`marcasMoto` (
  `id_marca` INT NOT NULL,
  `nombre_marca` VARCHAR(50) NOT NULL DEFAULT NULL,
  PRIMARY KEY (`id_marca`),
  CONSTRAINT ``
    FOREIGN KEY ()
    REFERENCES `workbenchmanager`.`vehiculo` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`modelos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`modelos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`modelos` (
  `id_marca` INT NULL DEFAULT NULL,
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `slug` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modelos_Marcas1_idx` (`id_marca` ASC) ,
  CONSTRAINT `fk_modelos_Marcas1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `workbenchmanager`.`Marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`modelosMoto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`modelosMoto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`modelosMoto` (
  `id_modelo` INT NOT NULL,
  `id_marca` INT NULL DEFAULT NULL,
  `nombre_modelo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_modelo`),
  INDEX `id_marca` (`id_marca` ASC) ,
  CONSTRAINT `modelosMoto_ibfk_1`
    FOREIGN KEY (`id_marca`)
    REFERENCES `workbenchmanager`.`marcasMoto` (`id_marca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`ordenes_trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`ordenes_trabajo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`ordenes_trabajo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(7) NOT NULL,
  `mantenimiento` VARCHAR(50) NULL DEFAULT NULL,
  `reparacion` VARCHAR(50) NULL DEFAULT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `fecha` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ordenes_trabajo_vehiculo1_idx` (`matricula` ASC) ,
  CONSTRAINT `fk_ordenes_trabajo_vehiculo1`
    FOREIGN KEY (`matricula`)
    REFERENCES `workbenchmanager`.`vehiculo` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`parte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`parte` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`parte` (
  `id_parte` INT NOT NULL AUTO_INCREMENT,
  `estado` BIT(1) NULL DEFAULT NULL,
  `factura` VARCHAR(255) NULL DEFAULT NULL,
  `facturado` BIT(1) NULL DEFAULT NULL,
  `fecha_entrada` DATE NOT NULL,
  `fecha_salida` DATE NULL DEFAULT NULL,
  `horas_estimadas` INT NOT NULL,
  `horas_reales` INT NULL DEFAULT NULL,
  `presupuesto` VARCHAR(255) NULL DEFAULT NULL,
  `presupuesto_firmado` BIT(1) NULL DEFAULT NULL,
  `cliente_dni` VARCHAR(9) NOT NULL,
  `id_mecanico` INT NOT NULL,
  `id_repuestos` INT NULL DEFAULT NULL,
  `id_vehiculo` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id_parte`),
  INDEX `FK5mjoos4q9b9wik6xenjtv8sec` (`cliente_dni` ASC) ,
  INDEX `FKp37mr2ll4g1xol7b0qo6ub451` (`id_mecanico` ASC) ,
  INDEX `FKfey5j1l1bnt6evox3855h86l` (`id_repuestos` ASC) ,
  INDEX `FKcwd0gq87h4pf1t8bj68da9gl6` (`id_vehiculo` ASC) ,
  CONSTRAINT `FK5mjoos4q9b9wik6xenjtv8sec`
    FOREIGN KEY (`cliente_dni`)
    REFERENCES `workbenchmanager`.`datos_personales` (`dni`),
  CONSTRAINT `FKcwd0gq87h4pf1t8bj68da9gl6`
    FOREIGN KEY (`id_vehiculo`)
    REFERENCES `workbenchmanager`.`vehiculo` (`matricula`),
  CONSTRAINT `FKfey5j1l1bnt6evox3855h86l`
    FOREIGN KEY (`id_repuestos`)
    REFERENCES `workbenchmanager`.`repuestos` (`id_repuestos`),
  CONSTRAINT `FKp37mr2ll4g1xol7b0qo6ub451`
    FOREIGN KEY (`id_mecanico`)
    REFERENCES `workbenchmanager`.`usuario_interno` (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`presupuestos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`presupuestos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`presupuestos` (
  `idPresupuesto` INT NOT NULL AUTO_INCREMENT,
  `cliente` VARCHAR(9) NOT NULL,
  `fechaCreacion` DATE NOT NULL,
  `estimacionCoste` DECIMAL(10,2) NOT NULL,
  `pdf` VARCHAR(255) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `datos_personales_dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idPresupuesto`),
  INDEX `fk_presupuestos_datos_personales1_idx` (`cliente` ASC) ,
  CONSTRAINT `fk_presupuestos_datos_personales1`
    FOREIGN KEY (`cliente`)
    REFERENCES `workbenchmanager`.`datos_personales` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`repuestos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`repuestos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`repuestos` (
  `id_repuestos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(19,2) NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`id_repuestos`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`server_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`server_info` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`server_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`usuario_interno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`usuario_interno` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`usuario_interno` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(100) NOT NULL,
  `rol` VARCHAR(10) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`usuario_web`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`usuario_web` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`usuario_web` (
  `dni` VARCHAR(9) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `UK_2u61cidjaivrc0jp5j57guqof` (`email` ASC) ,
  CONSTRAINT `fk_usuario_web_datos_personales1`
    FOREIGN KEY (`dni`)
    REFERENCES `workbenchmanager`.`datos_personales` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `workbenchmanager`.`vehiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `workbenchmanager`.`vehiculo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `workbenchmanager`.`vehiculo` (
  `matricula` VARCHAR(7) NOT NULL,
  `alta` BIT(1) NULL DEFAULT NULL,
  `anio` VARCHAR(4) NULL DEFAULT NULL,
  `foto` VARCHAR(100) NULL DEFAULT NULL,
  `km` INT NULL DEFAULT NULL,
  `marca` VARCHAR(50) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(11) NOT NULL,
  `cliente_dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `FKstcfjebr3gx0ysttuv0qw02wo_idx` (`cliente_dni` ASC) ,
  CONSTRAINT `FKstcfjebr3gx0ysttuv0qw02wo`
    FOREIGN KEY (`cliente_dni`)
    REFERENCES `workbenchmanager`.`datos_personales` (`dni`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
